name: Build and Deploy Site

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set Git Username and Email
      run: |
       git config user.name ${{ secrets.USERNAME }}
       git config user.email ${{ secrets.EMAIL }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn run deploy
      env:
        CI: true